name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed

      - name: Install Dependencies
        run: npm install
        working-directory: ./docs  # Set the working directory to the directory containing package.json

      - name: Build and Deploy
        run: |
          npm run build
          mv build ../docs  # Move the build output to the root of your repository
        working-directory: ./docs  # Set the working directory to the directory containing package.json

      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ secrets.GITHUB_ACTOR }}"
          git config --global user.email "${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com"
          git add ../docs  # Add the built files in the root directory
          git commit -m "Deploy to GitHub Pages"
          git push
        working-directory: ./docs  # Set the working directory to the directory containing package.json
